### ISSUE TITLE
Maven vs. Gradle

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#115]
Currently we have both a `maven` and a `gradle` build script. While the `gradle` build script is currently not functioning this should be easy to fix. Which leaves us with two build scripts that need to be updated. 

To make the process easier and to prevent strange errors when two people use different build systems I propose to remove one build system from Rails, i.e. either `maven` or `gradle`.

I don't have a preference currently which system I want to use in the future. Let us collect some advantages and disadvantages for the two systems so that we have a more objective view.

### Advantages of `Maven`
- `maven` uses `xml` for its build files which is not a programming language and therefore more restrictive compared to `gradle`. While this sounds like a disadvantage at first it can also be seen as an advantage because it makes the build configuration less magical, because it contains no code

### Advantages of `Gradle` 
- `gradle` build files are more compact and more on point, because they can be coded. They contain less boilerplate
- `gradle` supports the easy addition of additional tasks (for example to generate an installer etc.). You basically only need to write a new function which is then callable as a task from the terminal. This feature would be very useful to parameterize the installer creation call with `jpackage` with some information contained in the build configuration (for example the version number or jar filename in #114)

What do you think?

**Comment by jklap** [comment]
I'm for gradle. I've spent time with both and have built both simple and complex build scripts in both. I've spent much more time trying to fix "issues" in my maven projects.

I currently have working gradle build scripts for Rails (I'm no longer using the maven build nor anything in the target directory). I'll push those as a PR that can feed into this conversation.

One caveat, due to the changes in the JavaFX artifacts, the newer artifacts won't compile with a JDK less than 11 (not that compiled compat is still JDK 8). I haven't bothered to build support in the build script to compile under JDK 8 so that many need to be revisited if we want to retain that.

I also included a gradle GitHub workflow but that may need to be tweaked based on the previous comment regarding JDK 8.

Finally, I also tweaked the "version" and build date generating which changed where we pull the details from so there was a change in Config.

Please review 116 in the context of this discussion.

**Comment by blentz** [comment]
I have no preference. It sounds like gradle is the new hotness, so I'm okay migrating to that. 

Also, let's bump our JDK requirements to something recent. JDK 8 is really, really ancient. We don't need to support anything quite that old. So, let's establish the policy of only supporting N+1 versions of the JDK. The current version is 14, which means we should focus on supporting JDKs 13 and 14, but not worry about anything older.
