### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#2]
It would be quite useful to use a continuous integration tool (like travis-ci for example) to automatically do some tasks for us.
One such tasks would be to automatically run all tests, whenever a new PR has been opened or a commit to a branch has been made.
This would ensure that less commit with obvious/breaking bugs get pushed.

**Comment by neutronc** [comment]
You got some experience with that ? If so please talk to Brett Lentz about getting the necessary rights to set that up :)

Or tell me how to do it. 
Regards
Martin

**Comment by madoar** [comment]
I have some experience with travis-ci, but before I can do this I need to know how to run the tests, e.g. #1.

**Comment by neutronc** [comment]
Two different ways to run those.
Either using gradle and identify the necessary tasks "gradle tasks --all"
or inside eclipse you go to src/test/java rightclick on the packages and go for Run as Junit Test for each package.
Note that there will be failed tests in the net.sf.rails.test because the some of save games wont load or have differing output from the test generated reports. For report generation right click on net.sf.rails.test.testgamebuilder and go for run as Java Application.

**Comment by blentz** [comment]
I use Travis for some of my other projects. It's pretty easy to get set up. I support the idea of using it here. :+1:

**Comment by madoar** [comment]
I'll try to setup travis. If I need some additional permissions to do this I'll ask.
Before I can add travis we need to ensure that all tests can be run easily via a terminal command.
I solved this by #5 and #7, which introduce maven that allows us to run the tests via `mvn clean package`.

**Comment by neutronc** [comment]
Sorry forgot Travis is still missing

**Comment by madoar** [comment]
Travis is now enabled and configured.
You can see the current build status of `Rails` either in the README (https://github.com/Rails-18xx/Rails) or directly on the travis website (https://travis-ci.org/Rails-18xx/Rails).
