### ISSUE TITLE
1856 CGR Merger results in Tile Lay not possible on RC2.04

### ISSUE THREAD

**Issue by neutronc** [Rails-18xx/Rails#307]
we are playing 1856 with rails 2.04.
After the formation of the CGR with a Merger of the THB on L15 into CGR, no company can lay the Tile 59 on L15.
There is no popup-Question, in which direction the Token of the CGR former THB should be laid.

is this problem already solved in further releases or a new Bug?

**Comment by neutronc** [comment]
I think that behaviour is fixed in a later release though need to check.

**Comment by neutronc** [comment]
[1856_20201121_1655_Kllaus-J_rgen_Fleischer.zip](https://github.com/Rails-18xx/Rails/files/5595705/1856_20201121_1655_Kllaus-J_rgen_Fleischer.zip)

**Comment by erik-vos** [comment]
Fixed. 
The problem was, that PublicCompany.getHomeHexes() returns null if the company has no home hex(es), which applies to the CGR, whereas the calling code at ORUIManager.826 expects an empty list in such a case. Hence the game crashed with a NullPointer exception.
I have changed getHomeHexes() accordingly, and now it works as far as I can see: the expected token placement selection prompt does appear.
