### ISSUE TITLE
1835: game is broken after president dump

### ISSUE THREAD

**Issue by peter-de-boer** [Rails-18xx/Rails#352]
See the attached file. 
If president Pep tries to sell his 40% MS shares, the presidency is not changed to Stan.
Furthermore, the game seems broken in other ways as well after that. For example, if everyone passes, SX cannot finish its turn in the OR. At the end of the turn an error message pops up.
We are using rails-2.1beta1-all.jar .

[1835_20210301_0519_Pep.zip](https://github.com/Rails-18xx/Rails/files/6059604/1835_20210301_0519_Pep.zip)

**Comment by peter-de-boer** [comment]
Just looked around in recent issues. Is this related to #320?

**Comment by erik-vos** [comment]
That's a pretty old version of Rails that you are using, we are now post-2.4.0. With that new code, the program crashes before the end of your saved file: at the start of SR6 Hakko buys a PR share, while Rails thinks Pep has priority. That clearly is wrong, because Pep was the last buyer in SR5 (the BA presidency). If you can confirm that, then this is a bug we should first look at.
Quite possible that it is related to #320, which we thought had been fixed.

**Comment by peter-de-boer** [comment]
Where do you see that Rails thinks that Pep has priority at the start of SR6?
The log says correctly:

```
Start of Stock Round 6 ================== 
Hakko has the Priority Deal 
Hakko buys a 10% share of PR from IPO for 154M.
```

In know the version is not the latest, but it is what we are using. I guess it is not possible/useful to switch versions mid-game?
It would be great if we at least can continue this game somehow.

**Comment by erik-vos** [comment]
Apparently something has changed for the worse in the meantime. My log is different. 
Indeed usually switching versions is not a smart idea, but if progress is halted otherwise, you might have to.
I'll first try to fix that earlier crash, and then see where we are with your problem.
And it is not unthinkable to correct a saved file, in case it is outdated or buggy itself, but let's not assume that for now.

**Comment by erik-vos** [comment]
Fixed. Looks like having been a zero-day bug of at least Rails 2.x: in 1835, the priority was never set at a company start.
Buying a presidency always was a separate process, and that must have been overlooked whilst implementing 1835. It's probably rare to do that as a final action in a stock round. The MS can be dumped now and the PD is set correctly.

I cannot find an error with SX in the next OR, so I suppose that one has gone as well.

I'll push the fix.
@neutronc, perhaps it's possible to do a maintenance release after the PR, so Peter can continue his game?

**Comment by peter-de-boer** [comment]
So, do we need to move to a newer version now, or how can we continue?

**Comment by neutronc** [comment]
I can do a maintenance release on 2.4, so then you guys need to download that and as Erik said should be able to continue the game with the new version.

**Comment by peter-de-boer** [comment]
Ok, that is appreciated. When would that be available?

**Comment by peter-de-boer** [comment]
FYI, a new version is not so urgent for us. We just rolled back the game because one of the players had a rule misunderstanding (he thought the MS dump was not allowed at all because of the 40% shares still in the IPO). Now we seem to be able to continue the game with our current version.

**Comment by peter-de-boer** [comment]
We are about to start a new 1835 game. When will be the next release that includes this bug fix?
