### ISSUE TITLE
18EU: Won't let me lay a token in Berlin

### ISSUE THREAD

**Issue by jdgalt** [Rails-18xx/Rails#388]
At the point of this save file
[18EU_20210404_2006_OperatingRound 3.1.zip](https://github.com/Rails-18xx/Rails/files/6255273/18EU_20210404_2006_OperatingRound.3.1.zip)
, KBS attempts to place a token in Berlin/south, only to be denied with a message saying the space is reserved for some other company's home.  It isn't.

Rails 2.4.5+, on Ubuntu 17.10, 64 bit.

**Comment by jdgalt** [comment]
The message I get is "KBS cannot lay a base token on E10 for $0: Base token slot is reserved"

**Comment by erik-vos** [comment]
Changing Tiles.xml is a no-no, there is a better way to fix this, which I will do shortly. For now it will do.

It's the same problem as I encountered earlier in 18Scan: indeed the token relay part of the tile upgrade code cannot handle adding tokenable stations. I'm sure this worked in Rails 1.x, so I suppose it went wrong with Rails 2.0, when the code was rewritten by Stefan. Perhaps it's time to have another look at that code.

**Comment by erik-vos** [comment]
I have found and fixed the root cause of the problem, so that the artificial extra city on the yellow Berlin tile could be removed. This way, I did not need the other artificial fix that I had in mind. 

The problem was a confusion between stop number and related station number when creating a new Stop when a tile upgrade adds a new station. The once deprecated `legacyNumber` has been rehabilitated and now represents the actual stop number in stead of the related station number (and is equal to the stop id). This fixed the problem.
