### ISSUE TITLE
18Scan gets stuck at the place station token step. Impossible to continue

### ISSUE THREAD

**Issue by cmorenoserrano** [Rails-18xx/Rails#393]
I played 18Scan 3 times without trouble but the 4th time we got stuck at the place station token step, where the VR tried to skip the token step, but it was impossible. There was no way of moving onto the Set Revenue step.

I attach a screentshot, the logs and the save file.

[18Scan_log.zip](https://github.com/Rails-18xx/Rails/files/6292803/18Scan_log.zip)

[18Scan_20210411_2054_Dan.rails.zip](https://github.com/Rails-18xx/Rails/files/6292799/18Scan_20210411_2054_Dan.rails.zip)

![Screenshot 2021-04-11 at 21 58 58](https://user-images.githubusercontent.com/50919218/114321726-23f76880-9b14-11eb-880a-6ba77bca776b.png)

**Comment by erik-vos** [comment]
The problem here is, that the token step should have been skipped, exactly because there is nothing to do. And in such a case, the Skip button is not enabled. 

But here, the bonus step isn't skipped, because at the decision point the program incorrectly thinks that still a bonus token can be laid. Actually that is not the case, I suppose. But the check for that condition seems to be wrong.

This could be properly fixed, i.e. skipping the Token step if there is really nothing to do. However, this will have a bad effect on all saved files that include Skip actions that are not longer required, making these saved failes unloadable. In the current test set only one (18AL) file seems to have this particular (bonus token related) problem, but developers have and players may have other such files that they would rather keep to be loadable.

So, for the short term, the fix will be to re-enable the Skip button in the token step.

There is at least one more similar request: to skip the token step where the company does not have the money to lay a token (issue #379). That is easy to do, at least for games where tokens have a predetermined price, but it will also make Skip actions in saved files superfluous.

I am thinking about an update to address this once and for all: have the game loader skip any Skip actions that do not exist in the valid possible actions list. Such skips will not be processed, and consequently not appear in any new saved files. This way, spurious skip actions can easily be removed.

Opinions?

**Comment by jdgalt** [comment]
YES!!

**Comment by cmorenoserrano** [comment]
Yes, please!
Either option is fine by me. We don't mind clicking on Skip even if it's impossible/pointless to do anything if that helps people.
We had to end the game using a spreadsheet, so anything is better than that :)
Many thanks for the quick response!
