### ISSUE TITLE
1835 - change of PR director after discarding trains

### ISSUE THREAD

**Issue by weisswurst** [Rails-18xx/Rails#71]
The following happened in a 1835 game.
PR was already started, but not all minors had been merged yet.
Another company (SX) bought the first 5, so now all remaining minors merged, leading to two things:
- director change
- excess of trains

According to the rules (original german rules, rule 4.8), the change of director takes place before handling effects like exceeding the train limit.
Rails (2.0 RC3) asked the old director to discard trains though before the director change.

**Comment by neutronc** [comment]
This is a result of how rails can or rather cant handle player interactions. You need a gentleman agreement here to make sure nothing goes wrong as we cant jump forward to the new director as acting player in the current mechanismn.

**Comment by madoar** [comment]
@neutronc do you know what needs to be changed to provide the correct application behavior?

**Comment by neutronc** [comment]
@madoar : In principle you would have to rotate the OR internally through all players before checking the excess train routines. Since that is triggered by a new phase check.. and then have that active player now answer the games questions (non modal request) and rotate forward again to the player who did the last action i.e. buying the train without triggering all action phases...
Thats a complete nightmare to have a player act out of turn, and yes we still face that problem in 1870 or any other game that has price protections. Only way to solve that would be to trigger a new RoundType inside the OR (have a look at 1880 with the flexible OR handling due to trainrush..) Maybe a roundtype ExcessTrainDiscardingRound :).. But of course you would need to keep track of all side effects of teh director changes..

So..:)
