### ISSUE TITLE
18eu unpromotable tiles

### ISSUE THREAD

**Issue by walravenkoster** [Rails-18xx/Rails#78]
v2rc3: the protection on tiles on behalf of several minors leaves them indefenitely unpromotable after exchanging them for a major certificate. H3, K2, S6, U6, F9.

**Comment by neutronc** [comment]
This should be fixed in a later version already iirc.

Let me check

**Comment by neutronc** [comment]
Yes it was already fixed in a private test version.

Please find enclosed a test release. But be aware that this might break your game if you encountered a presidency dump. IN this case please upload your save game for me to fix it.

Regards
Martin
Win Version: [rails-2.0.RC5.8.zip](https://github.com/Rails-18xx/Rails/files/4021080/rails-2.0.RC5.8.zip)
Jar Version including Libs [Uploading rails-2.0.RC5.8-jar.zip…]()

Regards
Martin
